language: csharp
solution: Escapade.sln
before_install:
    - sudo apt-get install nunit-console
before_script:
    - nuget restore Escapade.sln
    - msbuild/p:Configuration=Debug-Windows Escapade.sln
    - msbuild/p:Platform="Any CPU" Escapade.sln
after_script:
    - nunit-console Escapade.Tests/bin/Release/Escapade.Tests.dll
